[package]
name = "vinilla-lib"
version = "0.1.0"
edition = "2021"

[lib]
name = "vinilla"
crate-type = ["cdylib"]

[dependencies]
vinilla-term = { path = "../vinilla-term" }
vte = { version = "0.12.0" }

[build-dependencies]
cbindgen = "0.26.0"
